services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Doing this unsyncs node_modules folder from host machine
    ports:
      - '3000:5173'
