services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    working_dir: /app

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Doing this fixes "Error: Cannot find module @rollup/rollup-linux-x64-gnu"
    ports:
      - '3000:5173'
    working_dir: /app
