name: Test and Deploy to Production

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare backend env file
        run: |
          echo "${{ secrets.ENV_PROD_BACKEND_CONTENT }}" > ./backend/.env.prod

      - name: Build and start services
        run: docker compose -f docker-compose.prod.yml up -d --build

      - name: Run backend tests
        run: docker compose -f docker-compose.prod.yml run --rm backend python manage.py test api

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PRODUCTION_PATH }}
            echo "${{ secrets.ENV_PROD_BACKEND_CONTENT }}" > ./backend/.env.prod
            ./deploy.sh
