name: Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'todo.txt'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare backend env file
        run: |
          echo "${{ secrets.ENV_PROD_BACKEND_CONTENT }}" > ./backend/.env.prod

      - name: Build and start services
        run: docker compose -f docker-compose.prod.yml up -d --build

      - name: Run backend tests
        run: docker compose -f docker-compose.prod.yml run --rm backend python -u manage.py test api
